# Supported funding platforms for this repository.
patreon: genuinemerit
github: genuinemerit            # If you enable GitHub Sponsors later
ko_fi: genuinemerit             # If you open Ko-fi
open_collective:                # e.g., saskan
liberapay:
buy_me_a_coffee:
tidelift:                       # e.g., pypi/saskan-app
custom:
  - https://genuinemerit.com/support
