[project]
name = "Saskantinon"
version = "0.0.0.a4"
description = "Saskan Lands Game"
authors = [{ name = "Genuine Merit Software", email = "genuinmemerit@pm.me" }]
keywords = ["game", "saskantinon", "RPG"]
license = "MIT"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: X11 Applications",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Topic :: Games/Entertainment :: Role-Playing",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "beautifulsoup4",
    "Levenshtein",
    "matplotlib",
    "networkx",
    "nltk",
    "numbers-parser",
    "numpy",
    "openai",
    "pandas",
    "pathlib",
    "pendulum",
    "pygame",
    "requests",
    "rich",
    "sqlalchemy",
    "tabulate",
    "tornado",
    "twisted",
    "tzlocal",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.project.scripts]
saskan = "scripts.manage:cli"

[project.urls]
"Bug Tracker" = "https://github.com/genuinemerit/saskan-app/issues"
"Documentation" = "https://github.com/genuinemerit/saskan-wiki"
"Source Code" = "https://github.com/genuinemerit/saskan-app"
"Story" = "https://github.com/genuinemerit/saskan-story"

[project.optional-dependencies]
testing = ["pytest", "coverage"]
linting = ["flake8", "pycodestyle"]
formatting = ["isort", "black"]
docs = ["sphinx"]

