#!/usr/bin/bash

# Be sure to chmod u=rwx,g=rx,o=rx
# This must be run with sudo permissions
# It should be run from the activated "saskan" venv
#  so that local directories are created there.

# @DEV: add logic to verify that the user is root

python3 ~APP_DIR~/python/saskan_install.py ~SRC_DIR~ ~TGT_DIR~ 

