INSERT INTO SASKAN_DB.moons (_id, name, relative_size, description)
VALUES 
   ('ENDR', 'Endor', 100, 'creative and destructive forces, metal, lava'),
   ('SELL', 'Sella', 90, 'joy, openness, reflection, lakes, marshes, wandering'),
   ('CALU', 'Calumbra', 70, 'radiance, fire, attachments, hearth, home'),
   ('ZEHM', 'Zehembra', 60, 'shaking, thunder, animal hordes, flood, earthquake'),
   ('SHNN', 'Shunna', 50, 'gentleness, wind, breeze, good air, calm'),
   ('KANK', 'Kanka', 35, 'abyss, gorge, waterfall, loss, edge of world, horizon'),
   ('JEMB', 'Jembor', 20, 'stillness, mountains, foreboding, mystery'),
   ('LELK', 'Lelako', 10, 'receptiveness, fertility, warm earth, bountiful waters');
