#!/usr/bin/bash

# Be sure to chmod u=rwx,g=rx,o=rx
# The installer script modifies this with the correct path
# Change this to execute a reporting script
# Replace this with functions in the Admin Tools app

python3 ~APP_DIR~io_wiretap.py

