# .github/workflows/test.yml
name: test

on:
  pull_request:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install deps & package
        run: poetry install --no-interaction --no-ansi

      - name: Run tests
        run: poetry run pytest -q
